### ISSUE TITLE
Inyectar datos de BANGUAT via API para tipo de cambio

### ISSUE THREAD

**Issue by Tropicalrambler** [sihaysistema/cambiare-gtq#1]
Obtener tipo de cambio USD GTQ
Crear dos registros por evento uno de Moneda origen a moneda destino, y otro de moneda destino a moneda origen.
Ambos son para compra y para venta simultáneamente.

usar API propio

**Comment by monroy95** [comment]
**Preview:**
![api_banguat](https://user-images.githubusercontent.com/26640728/62316294-5eaa9180-b454-11e9-82a2-5dd6ae2ed44b.gif)
