### ISSUE TITLE
Error al instalar cambiare desde la terminal

### ISSUE THREAD

**Issue by DanielVelasquezC** [sihaysistema/cambiare-gtq#27]
![image](https://user-images.githubusercontent.com/98435805/151085759-96a7e673-a894-4706-bc18-d699d33b21f9.png)

**Comment by monroy95** [comment]
El problema es la url para clonar, esta es la correta: 
```bash
bench get-app --branch production https://github.com/sihaysistema/cambiare-gtq.git
```
